---
  - name: Encrypt target data
    shell: printf "{{ master_password }}" | zncrypt-move encrypt @item.0 item.1 item.2
    with_together:
      - acl_categories
      - encryption_targets
      - mount_dirs
    when: item.0 is defined and item.1 is defined and item.2 is defined and {{ master_password }} is defined
    ignore_errors: yes