# Copyright 2014, Cloudera Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
  - name: Stat the storage directory to check for block-level
    stat: path={{ item.0 }} get_md5=no
    with_together:
      - storage_dirs
    register: st_storage

  - name: Create storage directories (if not present)
    file: path={{ item.0 }} state=directory owner=root group=root mode=700
    when: item.1.stat.isblk is not defined or item.1.stat.isblk == false
    with_together:
      - storage_dirs
      - st_storage.results

  - name: Create mount directories (if not present)
    file: path={{ item.0 }} state=directory owner=root group=root mode=700
    with_together:
      - mount_dirs

  - name: Get ztab contents
    command: cat /etc/zncrypt/ztab
    register: ztab_contents

  - name: Prepare system for encryption (create encrypted partitions)
    shell: printf "{{ master_password }}" | zncrypt-prepare {{ item.0 }} {{ item.1 }}
    with_together:
      - storage_dirs
      - mount_dirs
    when: master_password is defined and item.0 is defined and item.1 is defined and ztab_contents.stdout.find(item.1) == -1
